spring:
  datasource:
    url: jdbc:h2:tcp://localhost:9092/~/mydata/h2/hello
    driver-class-name: org.h2.Driver
    username: sa

  sql:
    init:
      mode: always
      encoding: UTF-8

  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    open-in-view: false

    generate-ddl: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  jooq:
    sql-dialect: h2

  h2:
    console:
      enabled: true
      path: /h2

  flyway:
    enabled: true
#    url: jdbc:h2:mem:hello
#    schemas: app_local
#    user: sa
#    locations: src/main/resources/db/migration/

#logging:
#  level:
#    p6spy: debug

decorator:
  datasource:
    p6spy:
      enable-logging: true